#cloud-config

# Other setup info for template (removed once processed)
ec2mc_template_info:
  AMI_info:
    AMI_ID: ami-5652ce39
    device_name: /dev/xvda
    default_user: ec2-user
  instance_type: t2.small
  volume_size: 8
  elastic_address: false
  security_groups:
  - ec2mc_sg
  write_directories:
  - local_dir: manage_scripts
    instance_dir: /home/ec2-user/manage-scripts/
    chmod: '0775'
  - local_dir: crontabs
    instance_dir: /etc/cron.d/

# add security patches and bug fixes
package_update: true
package_upgrade: true

# If you want certain packages installed
packages:
- screen

# Files copied from user_data template subdirectory(s) to write_files

# Commands to run on the instance
runcmd:
- [ sudo, yum, install, -y, java-1.8.0 ]
- [ sudo, yum, remove, -y, java-1.7.0-openjdk ]

# Reboot instance after completing setup
power_state:
  mode: reboot
  message: Rebooting
  timeout: 120

# Capture all subprocess output into a logfile
output: { all: '| tee -a /var/log/cloud-init-output.log' }
