#cloud-config
# add security patches and bug fixes
package_update: true
package_upgrade: true

# If you want certain packages installed
packages:
- screen

# Files copied from user_data template subdirectory(s) to write_files

# Commands to run on the instance
runcmd:
- [ sudo, yum, install, -y, java-1.8.0 ]
- [ sudo, yum, remove, -y, java-1.7.0-openjdk ]

# Reboot instance after completing setup
power_state:
  mode: reboot
  message: Rebooting
  timeout: 120

# Capture all subprocess output into a logfile
output: { all: '| tee -a /var/log/cloud-init-output.log' }
